
ALTER TABLE studio.workflows DISABLE ROW LEVEL SECURITY;
ALTER TABLE studio.executions DISABLE ROW LEVEL SECURITY;
ALTER TABLE studio.activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE studio.credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE studio.templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE studio.profiles DISABLE ROW LEVEL SECURITY;
