// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { GameDatabase } from './game-types';

const SUPABASE_URL = "https://sbgfyxaenvqujrbpmrdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZ2Z5eGFlbnZxdWpyYnBtcmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NzE0OTUsImV4cCI6MjA4NjQ0NzQ5NX0.P4qre-qe2VIl1gr89yFdmg2uivqizpSjZTaE70Fx9vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<GameDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});